routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Homepage
Route::get('/', function () {
    return view('home');
});

Route::get('/lang/{lang}', function ($lang) {
    Session::put('locale', $lang);
    return back();
})->name('langroute');

// Routes related to accounts. Register, login, logout, and passwordReset
Auth::routes();

Route::get('/admin', function () {
    if (Auth::check() && Auth::user()->isContentCreator()){
        return view('admin.home');
    }
    else return redirect('login');
});

// Settings page
Route::get('/admin/settings', 'CoreController@showEditPage');
Route::post('/admin/settings', 'CoreController@editSettings')->name('editSettings');

// Change page online status
Route::get('/admin/page/{slug}/setOnline/{setOnline}', 'PageController@setOnline')->name('page.setOnline');

// Show page
Route::get('/{slug}', 'PageController@show')->name('page.show');

// All page routes, expect for show
Route::resource('/admin/page', 'PageController')->except('create','show');
// Create page, with optional headPage parameter
Route::get('/admin/page/create/{headPage?}', 'PageController@create')->name('page.create');

resources/views/page/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('titles.create_page')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('page.store') }}">
                        @csrf

                        <h3>@lang('pages.details')</h3>
                        {{-- Online --}}
                        <div class="form-group row">
                            <label for="online" class="col-md-4 col-form-label text-md-right">@lang('pages.online')*</label>

                            <div class="col-md-6">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" name="isOnline" type="radio" id="isOnline_1" value="1" checked data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_online')">
                                    <label class="form-check-label" for="isOnline_1">@lang('general.yes')</label>
                                </div>

                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" name="isOnline" type="radio" id="isOnline_0" value="0" data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_offline')">
                                    <label class="form-check-label" for="isOnline_0">@lang('general.no')</label>
                                </div>
                            </div>
                        </div>

                        {{-- Title --}}
                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">@lang('pages.title')*</label>

                            <div class="col-md-6">
                                <input id="title" type="text"
                                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_title')">

                                @if($errors->has('title'))
                                    <span class="invalid-feedback">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        {{-- Head Page --}}
                        @if($headPage)
                            <div class="form-group row">
                                <label for="headPage" class="col-md-4 col-form-label text-md-right">@lang('pages.head_page')</label>

                                <div class="col-md-6">
                                    <input name="headPage" type="hidden" value="{{ $headPage->id }}">
                                    <input id="headPageTitle" type="text" class="form-control{{ $errors->has('headPageTitle') ? ' is-invalid' : '' }}" name="headPageTitle" value="{{ $headPage->title }}" disabled  data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_belongs_to_subpage')">
                                </div>
                            </div>
                        @endif

                        {{-- Content --}}
                        <div class="form-group row">
                            <textarea id="tinymce" name="tinymce"
                                      rows="10">{!! old(html_entity_decode('tinymce')) !!}</textarea>
                        </div>

                        {{--Submit--}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">@lang('general.save')</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/page/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('titles.edit_page')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('page.update', $page->id) }}">
                        @csrf
                        @method('PATCH')
                        <h3>@lang('pages.details')</h3>
                        @if($page->allowOnline())
                        {{-- Online --}}
                        <div class="form-group row">
                            <label for="online" class="col-md-4 col-form-label text-md-right">@lang('pages.online')*</label>

                            <div class="col-md-6">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" name="isOnline" type="radio" id="isOnline_1" value="1" {{ $page->isOnline ? 'checked' : '' }}  data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_online')">
                                    <label class="form-check-label" for="isOnline_1">@lang('general.yes')</label>
                                </div>

                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" name="isOnline" type="radio" id="isOnline_0" value="0" {{ !$page->isOnline ? 'checked' : '' }}  data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_offline')">
                                    <label class="form-check-label" for="isOnline_0">@lang('general.no')</label>
                                </div>
                            </div>
                        </div>
                        @endif

                        {{-- Title --}}
                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">@lang('pages.title')*</label>

                            <div class="col-md-6">
                                <input id="title" type="text"
                                       class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ $page->title }}" required autofocus  data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_title')">

                                @if($errors->has('title'))
                                    <span class="invalid-feedback">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        {{-- Head Page --}}
                        @if($page->headPage)
                            <div class="form-group row">
                                <label for="headPage" class="col-md-4 col-form-label text-md-right">@lang('pages.head_page')</label>

                                <div class="col-md-6">
                                    <input name="headPage" type="hidden" value="{{ $page->headPage->id }}">
                                    <input id="headPageTitle" type="text" class="form-control{{ $errors->has('headPageTitle') ? ' is-invalid' : '' }}" name="headPageTitle" value="{{ $page->headPage->title }}" disabled  data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_belongs_to_subpage')">
                                </div>
                            </div>
                        @endif

                        {{-- Content --}}
                        <div class="form-group row">
                            <textarea id="tinymce" name="tinymce">{!! html_entity_decode($page->content) !!}</textarea>
                        </div>

                        @if(Auth::check() && Auth::user()->isAdmin())
                            {{-- Radio's --}}

                            <h3>Admin settings</h3>
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <label for="currentURL" class="col-form-label">@lang('pages.current_url')</label>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-check form-check-inline">
                                        {{ route('page.show', $page->slug) }}
                                    </div>
                                </div>
                            </div>
                            {{-- Can change online --}}
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <label for="allowOnline" class="col-form-label">@lang('pages.online_changeable')</label>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowOnlineYes" name="allowOnline" value="1" {{ $page->allowOnline ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_online_changeable')">
                                        <label class="form-check-label" for="allowOnlineYes">@lang('general.yes')</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowOnlineNo" name="allowOnline" value="0" {{ !$page->allowOnline ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_online_changeable')">
                                        <label class="form-check-label" for="allowOnlineNo">@lang('general.no')</label>
                                    </div>
                                </div>
                            </div>

                            {{-- Can be edited by user --}}
                            {{-- Can change online --}}
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <label for="allowEdit" class="col-form-label">@lang('pages.editable')</label>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowEditYes" name="allowEdit" value="1" {{ $page->allowEdit ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_editable')">
                                        <label class="form-check-label" for="allowEditYes">@lang('general.yes')</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowEditNo" name="allowEdit" value="0" {{ !$page->allowEdit ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_editable')">
                                        <label class="form-check-label" for="allowEditNo">@lang('general.no')</label>
                                    </div>
                                </div>
                            </div>

                            {{-- Can be deleted by user --}}
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <label for="allowDelete" class="col-form-label">@lang('pages.deletable')</label>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowDeleteYes" name="allowDelete" value="1" {{ $page->allowDelete ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_deletable')">
                                        <label class="form-check-label" for="allowDeleteYes">@lang('general.yes')</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowDeleteNo" name="allowDelete" value="0" {{ !$page->allowDelete ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_deletable')">
                                        <label class="form-check-label" for="allowDeleteNo">@lang('general.no')</label>
                                    </div>
                                </div>
                            </div>

                            {{-- Can have sub-pages --}}
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <label for="allowSub" class="col-form-label">@lang('pages.may_have_sub')</label>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowSubYes" name="allowSub" value="1" {{ $page->allowSub ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_may_have_sub')">
                                        <label class="form-check-label" for="allowSubYes">@lang('general.yes')</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowSubNo" name="allowSub" value="0" {{ !$page->allowSub ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_may_have_sub')">
                                        <label class="form-check-label" for="allowSubNo">@lang('general.no')</label>
                                    </div>
                                </div>
                            </div>

                            {{-- Lock URL --}}
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <label for="allowLock" class="col-form-label">@lang('pages.lock_url_path')</label>
                                </div>
                                <div class="col-sm-9">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowLockYes" name="allowLock" value="1" {{ $page->allowLock ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_lock_url_path')">
                                        <label class="form-check-label" for="allowLockYes">@lang('general.yes')</label>
                                    </div>

                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="allowLockNo" name="allowLock" value="0" {{ !$page->allowLock ? 'checked' : '' }} data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_lock_url_path')">
                                        <label class="form-check-label" for="allowLockNo">@lang('general.no')</label>
                                    </div>
                                </div>
                            </div>
                        @endif

                        {{--Submit--}}
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">@lang('general.save')</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/page/overview.blade.php
@extends('layouts.app')

@section('content')

                <h2>@lang('titles.all_pages')</h2>
                <a href="{{ route('page.create') }}">
                <button class="btn" data-toggle="tooltip" data-placement="top" title="@lang('pages.tooltip_create_head') [level 1]">
                    <i class="fas fa-plus" style="color:green"></i> @lang('pages.create_new_page')
                </button>
                </a>
                <table class="table table-hover" style="margin-top: 10px;">
                    <tbody>
                    @php
                        $subPages = [];

                    @endphp
                    @forelse($relations as $relation)
                        {{-- Headpage that has no subpages [level 1] --}}
                        @if(empty($relation['subPageId']))
                            @php($page = $pages->where('id',$relation['id'])->first())
                            @include('page.overview.show',[$page, $sub = 0])
                        @else
                            {{-- Headpage that has subpages [level 1] --}}
                            @php(array_push($subPages, $relation['subPageId']))
                            @if(!in_array($relation['id'], $subPages))
                                @php($page = $pages->where('id',$relation['id'])->first())
                                @include('page.overview.show',[$page, $sub = 0])
                            @endif
                            {{-- Subpage that belongs to another subpage [level 3] --}}
                            @if(in_array($relation['id'], $subPages))
                                @php($page = $pages->where('id',$relation['subPageId'])->first())
                                @include('page.overview.show',[$page, $sub = 2])
                            @else
                                {{-- Subpage that belongs to a headpage [level 2] --}}
                                @php($page = $pages->where('id',$relation['subPageId'])->first())
                                @include('page.overview.show',[$page, $sub = 1])
                            @endif
                        @endif

                    @empty
                        <p>@lang('pages.no_pages')</p>
                    @endforelse
                    </tbody>
                </table>
@endsection

resources/views/page/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col">
            <h1>{{ $page->title }}</h1>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
            {!! html_entity_decode($page->content) !!}
        </div>
    </div>

@endsection