routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Homepage
Route::get('/', function () {
    return view('home');
});

Route::get('/lang/{lang}', function ($lang) {
    Session::put('locale', $lang);
    return back();
})->name('langroute');

// Routes related to accounts. Register, login, logout, and passwordReset
Auth::routes();

Route::get('/admin', function () {
    if (Auth::check() && Auth::user()->isContentCreator()){
        return view('admin.home');
    }
    else return redirect('login');
});

// Settings page
Route::get('/admin/settings', 'CoreController@showEditPage');
Route::post('/admin/settings', 'CoreController@editSettings')->name('editSettings');

// Change page online status
Route::get('/admin/page/{slug}/setOnline/{setOnline}', 'PageController@setOnline')->name('page.setOnline');

// Show page
Route::get('/{slug}', 'PageController@show')->name('page.show');

// All page routes, expect for show
Route::resource('/admin/page', 'PageController')->except('create','show');
// Create page, with optional headPage parameter
Route::get('/admin/page/create/{headPage?}', 'PageController@create')->name('page.create');

resources/views/admin/layouts/sidebar.blade.php
<nav id="sidebar">
    <div class="sidebar-header">
        <h3><a href="/">{{ $settings->get('name') }}</a></h3>
    </div>

    <ul class="list-unstyled components">
        <li class="{{ Request::is('admin') ? 'active' : '' }}"><a href="{{ url('/admin') }}">@lang('titles.home')</a></li>
        <li class="{{ Request::is('admin/settings') ? 'active' : '' }}"><a href="{{ route('editSettings') }}">@lang('titles.settings')</a></li>
        <li class="{{ Request::is('admin/page') ? 'active' : '' }}"><a href="{{ route('page.index') }}">@lang('titles.page_management')</a></li>
        {{--<li class="{{ Request::is('admin/translations') ? 'active' : '' }}"><a href="{{ url('/translations') }}">@lang('titles.translations')</a></li>--}}
    </ul>

</nav>